name: predictwell
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.18
  - pip
  - pip:
    - flask==2.0.1
    - werkzeug==2.0.3
    - flask-cors==3.0.10
    - gunicorn==20.1.0
    - numpy~=1.19.2
    - pandas==1.0.1
    - scikit-learn==0.24.2
    - xgboost==1.4.2
    - imbalanced-learn==0.8.0
    - joblib==1.0.1
    - pillow==8.3.1
    - tensorflow==2.5.0
    - keras==2.6.0
    - h5py==3.1.0
    - opencv-python-headless==4.5.3.56
    - matplotlib==3.4.2
    - seaborn==0.11.1
    - shap==0.39.0

